# Generated by Django 4.2.1 on 2023-06-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('product_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
