# Generated by Django 4.2.1 on 2023-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_new_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-created_at',), 'permissions': (('view_is_premium', 'Can view premium new'),)},
        ),
        migrations.AddField(
            model_name='new',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
